name: Compile 3DS

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set up devkitpro
        run: |
          # ensure apt is set up to work with https sources
          sudo apt-get install -y apt-transport-https
          
          # Add the devkitPro apt repository if we don't have it set up already
          sudo mkdir -p /usr/local/share/keyring/
          sudo wget -O /usr/local/share/keyring/devkitpro-pub.gpg https://apt.devkitpro.org/devkitpro-pub.gpg
          sudo echo "deb [signed-by=/usr/local/share/keyring/devkitpro-pub.gpg] https://apt.devkitpro.org stable main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
          
          sudo apt-get update
          sudo apt-get install -y devkitpro-pacman unzip

          sudo dkp-pacman --noconfirm -Syu
          sudo dkp-pacman --noconfirm -S 3ds-dev 3ds-curl
      - name: Get bannertool
        run: | 
          wget https://github.com/diasurgical/bannertool/releases/download/1.2.0/bannertool.zip
          unzip bannertool.zip
          chmod +x linux-x86_64/bannertool
      - name: Get ctrtool
        run: |
          wget https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18.4/makerom-v0.18.4-ubuntu_x86_64.zip
          unzip makerom-v0.18.4-ubuntu_x86_64.zip
          chmod +x makerom

      - run:  source /etc/profile.d/devkit-env.sh && PATH=$(pwd):$(pwd)/linux-x86_64/:$PATH && make cia
      - run: ls output